export const movies = [
  {
    id: 1,
    name: '盗梦空间',
    tags: ['逻辑', '潜意识', '结构'],
    dimension: 'NT',
  },
  {
    id: 2,
    name: '泰坦尼克号',
    tags: ['情感', '牺牲', '经典'],
    dimension: 'SF',
  },
  {
    id: 3,
    name: '肖申克的救赎',
    tags: ['希望', '毅力', '秩序'],
    dimension: 'SJ',
  },
  {
    id: 4,
    name: '瞬息全宇宙',
    tags: ['多元宇宙', '混乱美学', '存在主义'],
    dimension: 'NP',
  },
  { id: 5, name: '教父', tags: ['权力', '家庭', '原则'], dimension: 'SJ' },
  { id: 6, name: '小丑', tags: ['社会边缘', '心理', '反叛'], dimension: 'NF' },
  {
    id: 7,
    name: '速度与激情',
    tags: ['感官刺激', '动作', '直觉'],
    dimension: 'SP',
  },
  { id: 8, name: '星际穿越', tags: ['科学', '时空', '宏大'], dimension: 'NT' },
  {
    id: 9,
    name: '布达佩斯大饭店',
    tags: ['审美', '形式主义', '怀旧'],
    dimension: 'SJ',
  },
  {
    id: 10,
    name: '搏击俱乐部',
    tags: ['自我意识', '反物质', '破坏'],
    dimension: 'NT',
  },
  { id: 11, name: '千与千寻', tags: ['奇幻', '成长', '隐喻'], dimension: 'NF' },
  {
    id: 12,
    name: '华尔街之狼',
    tags: ['狂欢', '贪婪', '外向'],
    dimension: 'EP',
  },
  {
    id: 13,
    name: '奥本海默',
    tags: ['道德困境', '理智', '历史'],
    dimension: 'NT',
  },
  {
    id: 14,
    name: '当幸福来敲门',
    tags: ['奋斗', '写实', '情感'],
    dimension: 'SJ',
  },
  {
    id: 15,
    name: '疯狂的麦克斯4',
    tags: ['纯粹动作', '末世', '视觉'],
    dimension: 'SP',
  },
  { id: 16, name: '情书', tags: ['细腻', '暗恋', '含蓄'], dimension: 'IF' },
  { id: 17, name: '致命魔术', tags: ['反转', '执念', '精密'], dimension: 'NT' },
  { id: 18, name: '寄生虫', tags: ['阶级', '讽刺', '现实'], dimension: 'ST' },
  {
    id: 19,
    name: '寻梦环游记',
    tags: ['梦想', '家庭', '文化'],
    dimension: 'NF',
  },
  {
    id: 20,
    name: '低俗小说',
    tags: ['非线性', '黑色幽默', '酷'],
    dimension: 'NP',
  },
  {
    id: 21,
    name: '辛德勒的名单',
    tags: ['人性', '正义', '沉重'],
    dimension: 'SJ',
  },
  { id: 22, name: '黑客帝国', tags: ['真相', '虚拟', '觉醒'], dimension: 'NT' },
  {
    id: 23,
    name: '阿甘正传',
    tags: ['纯真', '历史', '顺其自然'],
    dimension: 'SJ',
  },
  { id: 24, name: '爱乐之城', tags: ['理想', '艺术', '遗憾'], dimension: 'NF' },
  {
    id: 25,
    name: '沉默的羔羊',
    tags: ['心理博弈', '惊悚', '观察'],
    dimension: 'INT',
  },
  {
    id: 26,
    name: '楚门的世界',
    tags: ['自由', '质疑', '觉悟'],
    dimension: 'NF',
  },
  {
    id: 27,
    name: '海上钢琴师',
    tags: ['孤独', '天赋', '精神世界'],
    dimension: 'IN',
  },
  {
    id: 28,
    name: '消失的爱人',
    tags: ['亲密关系', '算计', '冷酷'],
    dimension: 'TJ',
  },
  {
    id: 29,
    name: '被解救的姜戈',
    tags: ['暴力美学', '复仇', '释放'],
    dimension: 'SP',
  },
  { id: 30, name: '辩护人', tags: ['法律', '人权', '执着'], dimension: 'SJ' },
  { id: 31, name: '大鱼', tags: ['想象力', '童话', '和解'], dimension: 'NF' },
  {
    id: 32,
    name: '蝙蝠侠：黑暗骑士',
    tags: ['秩序', '混乱', '牺牲'],
    dimension: 'NTJ',
  },
  { id: 33, name: '美丽人生', tags: ['乐观', '父爱', '残酷'], dimension: 'NF' },
  {
    id: 34,
    name: '敦刻尔克',
    tags: ['沉浸感', '时间', '生存'],
    dimension: 'ST',
  },
  {
    id: 35,
    name: '这个杀手不太冷',
    tags: ['边缘', '救赎', '情感'],
    dimension: 'ISP',
  },
  {
    id: 36,
    name: '春光乍泄',
    tags: ['情绪', '破碎', '流浪'],
    dimension: 'IFP',
  },
  {
    id: 37,
    name: '辩护人',
    tags: ['社会责任', '勇气', '法治'],
    dimension: 'SJ',
  },
  { id: 38, name: '头号玩家', tags: ['怀旧', '游戏', '探索'], dimension: 'NP' },
  {
    id: 39,
    name: '剪刀手爱德华',
    tags: ['纯真', '孤独', '奇幻'],
    dimension: 'INFP',
  },
  { id: 40, name: '断背山', tags: ['压抑', '自然', '真挚'], dimension: 'ISF' },
  { id: 41, name: '荒野猎人', tags: ['意志', '原始', '残酷'], dimension: 'SP' },
  {
    id: 42,
    name: '一一',
    tags: ['生活哲学', '平淡', '视角'],
    dimension: 'INJ',
  },
  { id: 43, name: '猫鼠游戏', tags: ['模仿', '机智', '外向'], dimension: 'EP' },
  {
    id: 44,
    name: '禁闭岛',
    tags: ['悬疑', '精神分析', '阴谋'],
    dimension: 'NT',
  },
  {
    id: 45,
    name: '模仿游戏',
    tags: ['天才', '逻辑', '孤独'],
    dimension: 'INTJ',
  },
  { id: 46, name: '死亡诗社', tags: ['反抗', '浪漫', '启蒙'], dimension: 'NF' },
  { id: 47, name: '蝴蝶效应', tags: ['宿命', '改变', '因果'], dimension: 'NT' },
  {
    id: 48,
    name: '放牛班的春天',
    tags: ['教育', '音乐', '善良'],
    dimension: 'SJ',
  },
  {
    id: 49,
    name: '少年派的奇幻漂流',
    tags: ['信仰', '隐喻', '生存'],
    dimension: 'INF',
  },
  {
    id: 50,
    name: '爱在黎明破晓前',
    tags: ['沟通', '浪漫', '即兴'],
    dimension: 'ENP',
  },
];
